//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_Demo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Author> Tbl_Author { get; set; }
        public virtual DbSet<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual DbSet<Tbl_Post> Tbl_Post { get; set; }
        public virtual DbSet<Tbl_Rating> Tbl_Rating { get; set; }
        public virtual DbSet<Tbl_SocialNetwork> Tbl_SocialNetwork { get; set; }
        public virtual DbSet<Tbl_SocialNetworkType> Tbl_SocialNetworkType { get; set; }
    }
}
