//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Post()
        {
            this.Tbl_Comment = new HashSet<Tbl_Comment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AUTHOR_ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string URL { get; set; }
        public string CATEGORIES { get; set; }
        public Nullable<int> RATING_ID { get; set; }
    
        public virtual Tbl_Author Tbl_Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comment> Tbl_Comment { get; set; }
        public virtual Tbl_Rating Tbl_Rating { get; set; }
    }
}
