//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Rating()
        {
            this.Tbl_Post = new HashSet<Tbl_Post>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PERCENTAGE { get; set; }
        public Nullable<int> COUNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Post> Tbl_Post { get; set; }
    }
}
