//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Author
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BIO { get; set; }
        public string IMGURL { get; set; }
        public string PROFURL { get; set; }
    }
}
