//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphQL_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comment
    {
        public int ID { get; set; }
        public Nullable<int> POST_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string URL { get; set; }
        public Nullable<int> COUNT { get; set; }
    
        public virtual Tbl_Post Tbl_Post { get; set; }
    }
}
